#$ -M sylvain.marthey@inrae.fr
#$ -m ea
#$ -o ../mirdeep2/mirdeep2_clust.out
#$ -e ../mirdeep2/mirdeep2_clust.err
#$ -cwd
#$ -q infinit.q

# command(s):
# Se placer dans le bon répertoire
cd ../mirdeep2/

#Lancer mirdeep2

miRDeep2.pl ../mapper/processed_reads.fa \
../index/bosTau9.fa \
../mapper/reads_vs_genome_bta9.arf \
../mirbase22/mature_bta.fa \
../mirbase22/mature_no_bta.fa \
../mirbase22/hairpin_bta.fa \
-t Cow -P \
-g 100000 \
2> report_mirdeep2.pl.log
