#$ -M sylvain.marthey@jouy.inra.fr
#$ -m ea
#$ -o ../mirdeep2_clust.out
#$ -e ../mirdeep2_clust.err
#$ -cwd
#$ -q unlimitq
#$ -l mem=64G
#$ -l h_vmem=128G


# command(s):
Se placer dans le bon répertoire
cd ../quantifier/

#Lancer mirdeep2

miRDeep2.pl ../mapper/processed_reads.fa \
../index/bosTau8.fa \
../mapper/reads_vs_genome_bta8.arf \
..../quantifier/mature_bta.fa \
..../quantifier/mature_no_bta.fa \
..../quantifier/hairpin_bta.fa \
-t Cow -P \
-g 100000 \
2> report_mirdeep2.pl.log
